import Head from "next/head";

import Header from "../shared/header";
import CategorySection from "./category-section";
import HeroSection from "./hero-section";
import SellerList from "./seller-list";
import BannerSection from "./banner-section";
import { Provider } from "react-redux";
import { store } from "../store/store";

export default function HomePage() {
  return (
    <section>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header></Header>
      <HeroSection></HeroSection>
      <div className="px-12 pb-12">
        <Provider store={store}>
          <CategorySection></CategorySection>
          <SellerList></SellerList>
          <BannerSection></BannerSection>
        </Provider>
      </div>
    </section>
  );
}
